HOST = localhost
ASSETS_PORT = 1820
SERVER_PORT = 18200
API_PORT = 18201

export API_SERVER = $(HOST):$(API_PORT)
export ASSETS_SERVER = $(HOST):$(ASSETS_PORT)
export STATIC_PATH = $(PWD)/lib/frontend/static/
export STATIC_PATH = $(PWD)/lib/frontend/static/
export SERVER = $(HOST):$(SERVER_PORT)
export FLASK_APP = lib.backend
export FLASK_CONFIG = $(PWD)/lib/backend/application.cfg
export FLASK_TEST_CONFIG = $(PWD)/lib/backend/application-test.cfg
export FLASK_DEBUG = 1
# export USE_HTTP2 = y

# Python env
PYTHON_VERSION ?= python
VENV = $(PWD)/.env$(if $(filter $(PYTHON_VERSION),python),,-$(PYTHON_VERSION))
PIP = $(VENV)/bin/pip
PYTHON = $(VENV)/bin/python
PYTEST = $(VENV)/bin/py.test
FLASK = $(VENV)/bin/flask

# Node env
NODE_MODULES = $(PWD)/node_modules
NPM ?= yarn
