"""empty message

Revision ID: 41ea330e524d
Revises: 7acd9ca81b22
Create Date: 2017-11-21 15:36:36.036147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ea330e524d'
down_revision = '7acd9ca81b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainings',
    sa.Column('algorithm_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('last_train_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['corpus_categories.id'], ),
    sa.PrimaryKeyConstraint('algorithm_id', 'category_id')
    )
    op.drop_column('algorithms', 'last_train_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithms', sa.Column('last_train_date', sa.DATETIME(), nullable=True))
    op.drop_table('trainings')
    # ### end Alembic commands ###
